name: Build and Deploy
on:
    push:
        branches:
            - production

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Install
              run: yarn install
            
            - name: Build
              run: yarn run build

            - name: Generate Nuxt
              run: yarn run generate

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.7
              with:
                  branch: gh-pages
                  folder: dist
